DELETE FROM geek_interest;
DELETE FROM geek;
DELETE FROM interest;
DELETE FROM city;

insert INTO city values(0,'Lyon');
insert INTO city values(1,'Paris');
insert INTO city values(5,'Grenoble');
insert INTO city values(6,'Strasbourg');
insert INTO city values(7,'Toulouse');
insert INTO geek values(0,'Dupond','Kevin',1,'k3vin@caramail.com', '1985-01-01',0);
insert INTO geek values(1,'Ker','Julie',0,'julie31@hotmail.com', '1990-12-05',1);
insert INTO geek values(2,'Dupond','Paul',1,'paul@debian.com', '1980-01-01',0);
insert INTO interest values(0,'java');
insert INTO interest values(1,'C');
insert INTO interest values(2,'C++');
insert INTO interest values(3,'C#');
insert INTO interest values(4,'TDD');
insert INTO interest values(5,'JUnit');
insert INTO interest values(6,'PHP');
insert INTO interest values(7,'html');
insert INTO interest values(8,'html5');
insert INTO interest values(9,'css');
insert INTO interest values(10,'css3');
insert INTO GEEK_INTEREST values(0,0);
insert INTO GEEK_INTEREST values(0,1);
insert INTO GEEK_INTEREST values(1,0);
insert INTO GEEK_INTEREST values(1,2);
insert INTO GEEK_INTEREST values(2,0);
insert INTO GEEK_INTEREST values(2,1);
insert INTO GEEK_INTEREST values(2,2);